kind: pipeline
name: default

steps:
- name: scanner
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  #- sleep 5 # give docker enough time to start
  - docker ps -a
  - docker login registry.aquasec.com -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
  - docker pull registry.aquasec.com/scanner:2022.4
  - docker run -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan -H https://a23a3e4b89.cloud.aquasec.com/  -A 6f26ecbec88d8c45a244dd999a62f8c9440fad5b --local docker:dind

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
