kind: pipeline
name: default

steps:
- name: scanner
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  #- sleep 5 # give docker enough time to start
  - docker ps -a
  - docker login registry.aquasec.com -u $${regUser} -p $${regPass}
  - docker pull registry.aquasec.com/scanner:2022.4
  - docker run -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan -H $${aquaGW}  -A $${aquaToken} --local docker:dind
  environment:
    regUser:
      from_secret: regUser
    regPass:
      from_secret: regPass
    aquaGW:
      from_secret: aquaGW
    aquaToken:
      from_secret: aquaToken
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
